### ISSUE TITLE
Update HematoProvider to make it pure data provider

### ISSUE THREAD

**Issue by bekeles** [imsweb/mph#118]
1. Currently the 3 functions in the provider interface involve a logic. We want them to be pure data provider.
2. We also want to expose a function called "isHematoSamePrimary" which  uses hemato DBs same primary information.

**Comment by depryf** [comment]
Notifying @garybeverungen and @ctmay4 

@garybeverungen, I think SEER*Abs has an interface to show the multiple primary calculator (which only takes two morphology codes and two years and  returns a boolean.  I think you will need to call that new "MphUtils.getInstance().isHematoSamePrimary()" method for that feature.  But you will need for another release of this projet.

@bekeles can you also make the MphUtils constructor public, to allow other projects to create their own instance if needed. And please make sure to fix the warnings in MphUtils, I saw stuff like "variable should be final"; should be easy to fix.
