### ISSUE TITLE
Fix messages when we return questionable

### ISSUE THREAD

**Issue by bekeles** [imsweb/mph#22]
-Some are missing spaces.
- I may need to centralize the messages.

**Comment by depryf** [comment]
@halla-ims please review the messages for the existing rules and make sure there are no missing spaces. If you are not sure what you are looking for, please ask @bekeles

**Comment by bekeles** [comment]
Search for '"Unable to apply Rule"' with double quotes included. You will see I append the rule step after this message. It supposed to be '"Unable to apply Rule "' with space.

Another part of this issue is to centralize those questionable result messages somewhere and share them. Most of those results are because of unknown laterality and/or dx dates.
