### ISSUE TITLE
Change MphUtils.getAllGroups() to return a map

### ISSUE THREAD

**Issue by depryf** [imsweb/mph#23]
Searching for a group by ID is a common operation. It would be much more convenient if the getAllGroups() method returns a map of ID -> Group instead of just the groups in a list...

**Comment by bekeles** [comment]
We also need to modify the names of the group to put the year after the name like Colon (2007)

**Comment by depryf** [comment]
@halla-ims since you are about to make big changes to this project, can you please take care of this issue? Thanks.
