### ISSUE TITLE
Return INVALID_INPUT if inputs are missing or invalid

### ISSUE THREAD

**Issue by bekeles** [imsweb/mph#24]
Add a fourth return type INVALID_INPUT if site, hist, behavior or year is missing/invalid.

**Comment by depryf** [comment]
There are two sets of hist/behav I believe, ICD-O-3 and ICD-O-2; I assume one of the sets need to be provided? I guess we should also return invalid if the values are crossed (hist ICD-O-3 with behav ICD-O-2)? I guess providing both would not be an error, but in that case do we want to use the year to know which set to use? Not sure of the logic but I think we can figure out from other projects...

**Comment by bekeles** [comment]
The way we handle the histology and behavior is:
If year of diagnosis is before 2001 and if icd-o-2 codes are valid we use them, otherwise we use icd-o-3.
