### ISSUE TITLE
9392 should be included in 2 branches of chart 1.

### ISSUE THREAD

**Issue by bekeles** [imsweb/mph#31]
In the file MphConstants.java, the Map MALIGNANT_BRAIN_2007_CHART1 has duplicate key values of:
content.put("9392", "Embryonal tumors"); //Ependymoblastoma
content.put("9392", "Ependymal tumors"); //Anasplastic ependymoma
Does this need to be fixed?

This one is actually a bug. 9392 exists on both branches. So it should be same primary with both Embryonal tumors and Ependymal tumors. I will assign another issue for that.

The first thing to do here is to add two cases for unit test on M7. Histology pairs 9392, 9501 and 9392, 9393. Both pairs supposed to return single primary. Before the fix the test should fail.

**Comment by halla-ims** [comment]
I've added in the unit tests for Histology pairs 9392, 9501 and 9392, 9393. Only the first one fails. The second one passes OK since I think it's getting "Embryonal tumors" when it looks up 9392. I'll leave it in since it will fail if the first 9392 is removed from Chart1.
