### ISSUE TITLE
Add group ID and step to the output object

### ISSUE THREAD

**Issue by depryf** [imsweb/mph#6]
Right now it's available on each step, but as I confirmed with @bekeles, an output can only have one group. So I think that logically it makes sense to have a groupId field on the output.

**Comment by bekeles** [comment]
I remembered why I didn't add it at the first place. If two tumors are from different groups, multiple primary is returned. I guess we can return null group id on those cases.

**Comment by depryf** [comment]
Makes sense. But I agree we can return a null group ID. Pretty obvious it's no really applicable in that case!

**Comment by depryf** [comment]
I think we should also add the step that provided the result in the outer result (so both the group and the step will be the ones from the last applied rule; the reason is already the one from the last applied rule I believe. People might not care about the applied rules, but they might still care which group/step provided the result...

**Comment by depryf** [comment]
Tell me if I am wrong, but the group ID and the step will be the ones from the last applied rule, unless no rules got applied in which case they will be null. Is that accurate?
