### ISSUE TITLE
Remove Lenient mode

### ISSUE THREAD

**Issue by bekeles** [imsweb/mph#68]
This mode was added on purpose of an external library and that library is not using that mode anymore.

**Comment by depryf** [comment]
@bekeles could we take care of this one as well before we release?

**Comment by depryf** [comment]
Oops, I didn't realize we had software still using the mode. My bad.

**Comment by depryf** [comment]
@bekeles can't we remove the "lenient" mode now? Are we still waiting on something?

**Comment by bekeles** [comment]
Let me check.

**Comment by bekeles** [comment]
Well the external library :) using this has to do some cleanups before we make the changes here.
