### ISSUE TITLE
Update SEER API client

### ISSUE THREAD

**Issue by depryf** [imsweb/mph#79]
A new API client was released. I don't think it will affect anything in this project, but we should still upgrade.

We should also review all the other dependencies.

And for good measure, we should upgrade the diseases and drugs data (I am not aware that the data changed, but we might as well upgrade regardless).

**Comment by depryf** [comment]
@bekeles I updated the dependencies, you can ignore that part.

But I also tried to update the diseases, and the process ran for 2 minutes before I just gave up.

Could you please do that yourself (I think you are the one who added that lab class).

One thing I noticed is that the same primary files have "2010" in their name. Is that appropriate? Don't we use the "latest" data available?

**Comment by bekeles** [comment]
We use those files on the 2010 hematopoetic rules. We have another we use for the 2001 rules. I guess that is appropriate.
